#!/bin/bash

echo "============================================================================="
echo " Welcome... Setup My PC would make your pc look and feel like Samuel Amoah's "
echo "============================================================================="


#
# Installing utility console apps
# - Create a variable with the list of programs to install
# - Run apt-get install to install programs
#
programLists=(
	'git-all'
	'vim'
	'tree'
)

su -c apt-get install ${programList[@]} || (echo 'Error installing programs' && exit 2)


#
# Installing programs with different setup steps
# 1. Meteor
if hash meteor 2>/dev/null; then
else
	curl https://install.meteor.com/ | sh
fi

# 2. Ruby and Rails
if hash rvm 2>/dev/null; then
else
	curl -sSL https://get.rvm.io | bash -s stable --ruby
if

# check if rails is installed else install it
if hash rails 2>/dev/null; then
else
	gem install rails

#
# Terminal Configuration
# - Git configuration
git config --global user.name "Samuel Nkoom Amoah"
git config --global user.email "snamoah@gmail.com"

#
# Aliases
# (Read content from aliases file and append into .bashrc file in /home directory
#
#
cat aliases >> ~/.bashrc
exec bash


#
# - Install vim plugins
#
# First verify if ~/.vim/bundle folder exists else create it
#
cat vim-plugins >> ~/.vimrc
vim +PluginInstall +qall # install plugins 
